---

# Set hostname
host_name: ransibley-pi

# New user
user_name: pi
user_group: sudo

# Public key to upload to the new user
ssh_pub_key: ~/.ssh/id_rsa.pub

apt_keys:
  - { keyserver: 'pgpkeys.mit.edu', id: 'CCD91D6111A06851' } #repozytorium.mati75.eu

# Sources need "tor+" prefix, since we're fetching via tor!
apt_sources:
  - deb tor+http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free

# Install necessary packages
apt_install_packages:
  - pwgen #required for user password generation!
  - curl
  - git
  - glances
  - nano
  - openssl

# Remove any specified packages
apt_remove_packages:
#  - package_name

# Nginx
# server_name: _
# web_root: /var/www/html
