---

# New user
user_name: raspi
user_pass: # if empty one will be generated!
user_group: sudo

# Public key to upload to the new user
ssh_pub_key: ~/.ssh/id_rsa.pub

# Install necessary packages
install_packages:
  - pwgen #required!
  - curl
  - git
  - glances
  - nano
  - openssl

remove_packages:
#  - package_name

apt_sources:
  - {d: 'deb', u: 'http://repozytorium.mati75.eu/raspbian', p: 'jessie-backports main contrib non-free'}

# Nginx
server_name: _
web_root: /var/www/html
